### ISSUE TITLE
5.1	Reveal hidden text.

### ISSUE THREAD

**Issue by oubaka** [oubaka/jqfundamentals-1#4]
https://github.com/oubaka/jqfundamentals-1/blob/master/exercises/js/blog.js

Open the file /exercises/index.html in your browser. Use the file /exercises/js/blog.js. Your task is to add some interactivity to the blog section of the page. The spec for the feature is as follows:
Clicking on a headline in the #blog div should slide down the excerpt paragraph
Clicking on another headline should slide down its excerpt paragraph, and slide up any other currently showing excerpt paragraphs.

**Comment by segunadeleye** [comment]
This can be achieved in much fewer DOM traversal.
Use 2-space indentation

**Comment by oubaka** [comment]
Correction made as adviced

**Comment by segunadeleye** [comment]
Looks good...however there is no need to save `$(this)` in a variable.
